packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@vercel/vc-native-darwin-arm64@62.1.0'
  - '@vercel/vc-native-darwin-x64@62.1.0'
  - '@vercel/vc-native-linux-arm64@62.1.0'
  - '@vercel/vc-native-linux-x64@62.1.0'
  - '@vercel/vc-native-win32-arm64@62.1.0'
  - '@vercel/vc-native-win32-x64@62.1.0'
  - vercel@62.1.0

overrides:
  uuid@<11.1.1: 11.1.1
