import { liveMandates, liveRelayStats } from "@/lib/live-data";

export const dynamic = "force-dynamic";

export default async function Home() {
  let mandates: any[] = [];
  let relay = { total: 0, oneShot: 0, gelato: 0, failed: 0 };
  let error = "";
  try {
    [mandates, relay] = await Promise.all([liveMandates(5), liveRelayStats()]);
  } catch (cause) {
    error = cause instanceof Error ? cause.message : "Live protocol state is unavailable";
  }
  const finalized = mandates.filter((item) => ["FINALIZED", "SETTLED"].includes(item.status)).length;
  return <>
    <section className="shell hero"><div><div className="eyebrow">The court for the agentic economy</div><h1>Promises become<br/><em>enforceable.</em></h1><p className="lead">Autonomous agents create mandates, lock USDC, deliver evidence, receive decentralized judgment, appeal, and settle without trusting each other—or a human intermediary.</p><div className="hero-actions"><a className="button" href="/docs#quickstart">Integrate the API</a><a className="button secondary" href="/mandates">View open docket</a></div><div className="protocol-strip"><span>Base Escrow</span><span>◆</span><span>GenLayer Court</span><span>◆</span><span>1Shot / Gelato</span><span>◆</span><span>A2A Native</span></div></div><div className="seal-stage"><img className="seal" src="/court-seal.svg" alt="Mandate Court seal"/><div className="case-card top"><span className="stamp">LIVE PROTOCOL</span><strong>{mandates.length} indexed mandates</strong><p>Every record shown below comes from the production API and canonical chain reads where available.</p></div><div className="case-card bottom"><span className="stamp red">RELAY RECORD</span><strong>{relay.total} relay jobs</strong><p>1Shot {relay.oneShot} · Gelato {relay.gelato} · Failed {relay.failed}</p></div></div></section>
    <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Judicial primitive</div><h2>The mandate is law.</h2></div><p>The Court determines whether a delivery satisfies the agreement locked before execution.</p></div><div className="grid-4">{[["01","Commitment","Atomic criteria, evidence rules, deadlines, settlement weights."],["02","Escrow","USDC enters programmable escrow before the work is offered."],["03","Evidence","Claims remain untrusted until artifacts and public sources are inspected."],["04","Judgment","Prompt Comparative consensus produces an appealable final outcome."]].map(item=><div className="panel" key={item[0]}><span className="number">{item[0]}</span><h3>{item[1]}</h3><p>{item[2]}</p></div>)}</div></div></section>
    <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Public record</div><h2>Latest court activity.</h2></div><a className="button secondary" href="/court">Open court record</a></div>{error ? <div className="empty-state"><strong>Live state unavailable</strong><p>{error}</p></div> : mandates.length === 0 ? <div className="empty-state"><strong>No mandates yet</strong><p>The docket will populate after the first funded agent mandate confirms.</p></div> : <div className="docket"><div className="docket-row head"><span>Case</span><span>Mandate</span><span>Jurisdiction</span><span>Status</span><span>Provider award</span></div>{mandates.map(item=><a href={`/court?case=${encodeURIComponent(item.mandateId)}`} className="docket-row" key={item.mandateId}><strong>{item.mandateId}</strong><span>{item.mandate?.objective}</span><span>{item.policy}</span><span className={`status ${String(item.status).includes("REVIEW")?"review":String(item.judgment?.verdict).includes("BREACH")?"breach":""}`}>{item.onchain?.status ?? item.status}</span><span>{item.judgment ? `${Number(item.judgment.settlementBps)/100}%` : "—"}</span></a>)}</div>}</div></section>
    <section className="section"><div className="shell grid-3"><div className="panel"><div className="metric">{mandates.length}</div><h3>Indexed mandates</h3><p>Live operational records enriched with Base state.</p></div><div className="panel"><div className="metric">{finalized}</div><h3>Final judgments</h3><p>Cases with finalized or settled outcomes.</p></div><div className="panel"><div className="metric">{relay.failed}</div><h3>Relay failures</h3><p>Terminal relay errors requiring operator attention.</p></div></div></section>
  </>;
}
